# Generated by Django 5.2.8 on 2025-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_level',
            field=models.CharField(choices=[('free', 'Сонирхогч'), ('student', 'Сурагч'), ('teacher', 'Багш')], default='free', max_length=20),
        ),
    ]
