# Generated by Django 5.2.8 on 2025-12-01 04:43

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, validators=[courses.validators.validate_youtube_url]),
        ),
    ]
