# Generated by Django 5.2.8 on 2025-11-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ямар хичээл үзмээр байна вэ?', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Яг ямар агуулга, сэдвүүд орвол зүгээр гэж бодож байгаагаа бичнэ үү.')),
                ('desired_level', models.CharField(blank=True, choices=[('beginner', 'Анхан шат'), ('intermediate', 'Дунд шат'), ('advanced', 'Ахисан шат')], max_length=20)),
                ('name', models.CharField(blank=True, help_text='Нэр (заавал биш)', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='И-мэйл (заавал биш)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Шинэ'), ('review', 'Хянагдаж байна'), ('planned', 'Төлөвлөсөн'), ('done', 'Хийгдсэн'), ('rejected', 'Хүлээж аваагүй')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseWishComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Таны нэр', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(help_text='Сэтгэгдэл, санал, зөвлөгөө')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='student.coursewish')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
