# Generated by Django 5.2.8 on 2025-12-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursewish',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursewish',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='coursewish',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coursewish',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coursewishcomment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursewishcomment',
            name='text',
            field=models.TextField(),
        ),
    ]
